//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWorkTwo
{
    using System;
    using System.Collections.Generic;

    public partial class fandv
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Color { get; set; }
        public int Calories { get; set; }

        public fandv()
        {
           
        }

        public fandv(int id, string name, string type, string color, int calories)
        {
            Id = 5;
            Name = name;
            Type = type;
            Color = color;
            Calories = calories;
        }
        public override string ToString()
        {
            return Id.ToString() + " " + Name + " " + Color + " " + Calories.ToString();
        }
    }


}
